# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  DB_HOST: cyrkl-postgres                      
  DB_DRIVER: postgres
  API_SECRET: 98hbun98h                            # Used for creating a JWT
  DB_USER: root
  DB_PASSWORD: apirestgo
  DB_NAME: cyrkl
  DB_PORT: 5432

# Used by pgadmin service 
  PGADMIN_DEFAULT_EMAIL: live@admin.com
  PGADMIN_DEFAULT_PASSWORD: password

# Postgres Test
  TEST_DB_HOST: postgres_test                      
# TEST_DB_HOST=127.0.0.1                        # when running the app without docker 
  TEST_DB_DRIVER: postgres
  TEST_API_SECRET: 98hbun98h
  TEST_DB_USER: root
  TEST_DB_PASSWORD: apirestgo
  TEST_DB_NAME: cyrkl_api_test
  TEST_DB_PORT: 5432
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
